import type {
  AccountOperationRecord,
  AiModelGrantRecord,
  AiModelRecord,
  MemberRecord,
  ModuleCardStat,
  ProductAgentRecord,
  ProductModelPolicyRecord,
  ProductReleaseRecord,
  ProductSolutionRecord,
  QuickAction,
  SessionSnapshot,
  SummaryMetric,
  TenantOperationRecord,
} from '@/entities/console';
import { resolveIpLocation } from './ip-location';

export const mockAuthenticatedSession: SessionSnapshot = {
  isAuthenticated: true,
  user: {
    id: 'platform_admin_mock',
    name: 'Super Admin',
    email: 'superadmin@local.vxture',
    roleLabel: 'Super Admin',
    username: 'superadmin',
    phone: '13800000000',
  },
  capabilities: [
    'platform.admin.manage',
    'platform.tenant.manage',
    'platform.product.manage',
    'platform.pricing.manage',
    'platform.model.manage',
  ],
};

export const anonymousSession: SessionSnapshot = {
  isAuthenticated: false,
  user: null,
  capabilities: [],
};

export const dashboardStats: ModuleCardStat[] = [
  {
    label: 'Current plan',
    value: 'Growth',
    hint: 'Renews on May 18, 2026 with pooled workspace billing.',
  },
  {
    label: 'Quota health',
    value: '78%',
    hint: 'Inference remains healthy, but GPU tuning is approaching alert range.',
  },
  {
    label: 'Open reminders',
    value: '3',
    hint: 'One invoice, one invite, and one quota threshold need review.',
  },
];

export const memberMetrics: SummaryMetric[] = [
  {
    label: 'Members',
    value: '128',
    trend: '+6 this month',
    tone: 'positive',
  },
  {
    label: 'Pending invites',
    value: '7',
    trend: '2 need follow-up',
    tone: 'warning',
  },
  {
    label: 'Admin coverage',
    value: '4',
    trend: '2 primary owners',
  },
];

export const subscriptionHighlights: ModuleCardStat[] = [
  {
    label: 'Plan',
    value: 'Growth',
    hint: '120 seats, shared inference pool, and enterprise support.',
  },
  {
    label: 'Renewal',
    value: 'May 18',
    hint: 'Annual renewal remains editable before invoice lock.',
  },
  {
    label: 'Projected overage',
    value: '¥1,280',
    hint: 'Driven by model access bursts in the current month.',
  },
];

export const billingMetrics: SummaryMetric[] = [
  {
    label: 'Outstanding',
    value: '¥8,420',
    trend: 'Due in 5 days',
    tone: 'warning',
  },
  {
    label: 'Paid this cycle',
    value: '¥26,900',
    trend: 'On track',
    tone: 'positive',
  },
  {
    label: 'Payment method',
    value: 'Corporate Visa',
    trend: 'Expires 09/2027',
  },
];

export const quotaMetrics: SummaryMetric[] = [
  {
    label: 'Inference credits',
    value: '64%',
    trend: 'Healthy',
    tone: 'positive',
  },
  {
    label: 'Fine-tune budget',
    value: '91%',
    trend: 'Approaching cap',
    tone: 'warning',
  },
  {
    label: 'Seat usage',
    value: '84 / 120',
    trend: '36 seats available',
  },
];

export const quickActions: QuickAction[] = [
  {
    label: 'Add member',
    description: 'Invite operators, workspace owners, and readonly reviewers.',
    href: '/members',
    icon: 'users',
  },
  {
    label: 'Review subscription',
    description: 'Inspect plan details, renewal timing, and quota pool pressure.',
    href: '/subscription',
    icon: 'chart-bar',
  },
  {
    label: 'Adjust quotas',
    description: 'Rebalance shared limits before overage costs increase.',
    href: '/quotas',
    icon: 'database',
  },
];

export const memberRecords: MemberRecord[] = [
  {
    id: 'm_01',
    accountId: 'a_01',
    name: 'Lin Chen',
    username: 'lin.chen',
    avatarUrl: null,
    email: 'lin.chen@vxture.ai',
    phone: '13800001001',
    role: 'Owner',
    roleCode: 'owner',
    roleId: 'role_owner',
    status: 'Active',
    statusCode: 'active',
    lastActive: '5 minutes ago',
    team: 'Platform Operations',
    joinedAt: '2026-04-01T08:00:00.000Z',
    isPrimaryOwner: true,
  },
  {
    id: 'm_02',
    accountId: 'a_02',
    name: 'Mika Zhou',
    username: 'mika.zhou',
    avatarUrl: null,
    email: 'mika.zhou@vxture.ai',
    phone: '13800001002',
    role: 'Billing Admin',
    roleCode: 'admin',
    roleId: 'role_admin',
    status: 'Active',
    statusCode: 'active',
    lastActive: '1 hour ago',
    team: 'Finance',
    joinedAt: '2026-04-05T08:00:00.000Z',
    isPrimaryOwner: false,
  },
  {
    id: 'm_03',
    accountId: 'a_03',
    name: 'Jun Park',
    username: 'jun.park',
    avatarUrl: null,
    email: 'jun.park@vxture.ai',
    phone: '13800001003',
    role: 'Workspace Admin',
    roleCode: 'admin',
    roleId: 'role_admin',
    status: 'Invited',
    statusCode: 'inactive',
    lastActive: 'Invitation sent today',
    team: 'Delivery',
    joinedAt: '2026-04-18T08:00:00.000Z',
    isPrimaryOwner: false,
  },
  {
    id: 'm_04',
    accountId: 'a_04',
    name: 'Ava Song',
    username: 'ava.song',
    avatarUrl: null,
    email: 'ava.song@vxture.ai',
    phone: '13800001004',
    role: 'Analyst',
    roleCode: 'member',
    roleId: 'role_member',
    status: 'Suspended',
    statusCode: 'banned',
    lastActive: '12 days ago',
    team: 'Security Review',
    joinedAt: '2026-03-28T08:00:00.000Z',
    isPrimaryOwner: false,
  },
  {
    id: 'm_05',
    accountId: 'a_05',
    name: 'Noah Xu',
    username: 'noah.xu',
    avatarUrl: null,
    email: 'noah.xu@vxture.ai',
    phone: '13800001005',
    role: 'Member',
    roleCode: 'member',
    roleId: 'role_member',
    status: 'Active',
    statusCode: 'active',
    lastActive: 'Yesterday',
    team: 'Applied AI',
    joinedAt: '2026-04-10T08:00:00.000Z',
    isPrimaryOwner: false,
  },
];

export const invoiceRows = [
  ['INV-2026-0418', 'Apr 18, 2026', 'Growth annual', 'Paid', '¥26,900'],
  ['INV-2026-0318', 'Mar 18, 2026', 'Model overage', 'Due', '¥8,420'],
  ['INV-2026-0218', 'Feb 18, 2026', 'Seat expansion', 'Paid', '¥4,600'],
];

export const quotaRows = [
  ['Inference requests', '9.2M / 12M', '76%', 'Healthy'],
  ['Fine-tune GPU hours', '182 / 200', '91%', 'Watch'],
  ['Knowledge indexing', '4.1TB / 6TB', '68%', 'Healthy'],
];

export const aiModelRecords: AiModelRecord[] = [
  {
    id: 'aimodel_doubao_seed_lite',
    providerId: null,
    modelCode: 'doubao-seed-2-0-lite-260215',
    modelName: 'Doubao Seed 2.0 Lite',
    provider: 'doubao',
    endpointUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocol: 'openai-compatible',
    capabilities: ['text', 'tool-call'],
    apiKeyEnvVar: 'DOUBAO_API_KEY',
    isActive: true,
    config: null,
    createdAt: '2026-04-25T08:00:00.000Z',
    updatedAt: '2026-04-25T08:00:00.000Z',
  },
  {
    id: 'aimodel_doubao_seed_pro',
    providerId: null,
    modelCode: 'doubao-seed-2-0-pro-260215',
    modelName: 'Doubao Seed 2.0 Pro',
    provider: 'doubao',
    endpointUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocol: 'openai-compatible',
    capabilities: ['text', 'tool-call', 'reasoning'],
    apiKeyEnvVar: 'DOUBAO_API_KEY',
    isActive: true,
    config: null,
    createdAt: '2026-04-25T08:05:00.000Z',
    updatedAt: '2026-04-25T08:05:00.000Z',
  },
  {
    id: 'aimodel_doubao_seed_code',
    providerId: null,
    modelCode: 'doubao-seed-2-0-code-preview-260215',
    modelName: 'Doubao Seed 2.0 Code',
    provider: 'doubao',
    endpointUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    protocol: 'openai-compatible',
    capabilities: ['text', 'tool-call', 'code'],
    apiKeyEnvVar: 'DOUBAO_API_KEY',
    isActive: true,
    config: null,
    createdAt: '2026-04-25T08:08:00.000Z',
    updatedAt: '2026-04-25T08:08:00.000Z',
  },
  {
    id: 'aimodel_claude_sonnet',
    providerId: null,
    modelCode: 'claude-sonnet-4-20250514',
    modelName: 'Claude Sonnet',
    provider: 'claude',
    endpointUrl: 'https://api.anthropic.com',
    protocol: 'anthropic-messages',
    capabilities: ['text', 'reasoning'],
    apiKeyEnvVar: 'ANTHROPIC_API_KEY',
    isActive: true,
    config: { anthropicVersion: '2023-06-01' },
    createdAt: '2026-04-25T08:10:00.000Z',
    updatedAt: '2026-04-25T08:10:00.000Z',
  },
  {
    id: 'aimodel_private_qwen',
    providerId: null,
    modelCode: 'private-qwen-72b',
    modelName: 'Private Qwen 72B',
    provider: 'private',
    endpointUrl: 'http://localhost:8008/v1',
    protocol: 'openai-compatible',
    capabilities: ['text', 'private'],
    apiKeyEnvVar: 'PRIVATE_QWEN_API_KEY',
    isActive: false,
    config: null,
    createdAt: '2026-04-25T08:20:00.000Z',
    updatedAt: '2026-04-25T08:20:00.000Z',
  },
];

export const aiModelGrantRecords: AiModelGrantRecord[] = [
  {
    id: 'grant_demo_doubao',
    modelId: 'aimodel_doubao_seed_lite',
    tenantId: 'tenant_demo',
    agentId: null,
    priority: 100,
    reason: '平台默认在线模型',
    expiresAt: null,
    isActive: true,
    createdAt: '2026-04-25T08:30:00.000Z',
    updatedAt: '2026-04-25T08:30:00.000Z',
  },
  {
    id: 'grant_demo_doubao_pro',
    modelId: 'aimodel_doubao_seed_pro',
    tenantId: 'tenant_demo',
    agentId: null,
    priority: 90,
    reason: '平台默认在线增强模型',
    expiresAt: null,
    isActive: true,
    createdAt: '2026-04-25T08:32:00.000Z',
    updatedAt: '2026-04-25T08:32:00.000Z',
  },
  {
    id: 'grant_demo_doubao_code',
    modelId: 'aimodel_doubao_seed_code',
    tenantId: 'tenant_demo',
    agentId: null,
    priority: 80,
    reason: '平台默认代码模型',
    expiresAt: null,
    isActive: true,
    createdAt: '2026-04-25T08:34:00.000Z',
    updatedAt: '2026-04-25T08:34:00.000Z',
  },
  {
    id: 'grant_demo_private',
    modelId: 'aimodel_private_qwen',
    tenantId: 'tenant_demo',
    agentId: 'agent-emergency-command',
    priority: 20,
    reason: '应急管理行业方案灰度接入',
    expiresAt: '2026-12-31T15:59:59.000Z',
    isActive: false,
    createdAt: '2026-04-25T08:35:00.000Z',
    updatedAt: '2026-04-25T08:35:00.000Z',
  },
];

export const productAgentRecords: ProductAgentRecord[] = [
  {
    id: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    description: '面向 console 平台的对话型智能助手，先用于模型策略和计量链路验证。',
    agentType: 'chat',
    status: 'active',
    visibility: 'internal',
    defaultModelCode: 'doubao-seed-2-0-lite-260215',
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
  {
    id: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    description: '统一命名为 ruyinagent，验证阶段先以对话智能体接入。',
    agentType: 'chat',
    status: 'active',
    visibility: 'public',
    defaultModelCode: 'doubao-seed-2-0-lite-260215',
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
];

export const productSolutionRecords: ProductSolutionRecord[] = [
  {
    id: 'solution-flood-regulation',
    solutionCode: 'flood-regulation',
    solutionName: '洪涝灾害监管业务',
    description: '面向水利、应急和城市治理客户的洪涝灾害监管方案，覆盖低空巡检、视频解译、调度协同、数据沉淀和报告编制。',
    industry: '应急管理 / 水利监管',
    scenario: '洪涝灾害监管',
    customerSegment: '省市应急、水利部门、园区管委会',
    status: 'active',
    visibility: 'public',
    ownerTeam: '行业解决方案组',
    subscriptionCount: 12,
    activeTenantCount: 10,
    monthlyRevenue: 128000,
    tags: ['低空巡检', '视频解译', '应急调度'],
    products: [
      { id: 'flood-drone-platform', productCode: 'drone-platform', productName: '无人机平台', productType: 'platform', source: 'partner', role: '飞行任务与设备接入', status: 'active' },
      { id: 'flood-dispatch-agent', productCode: 'dispatch-agent', productName: '智能调度智能体', productType: 'agent', source: 'self', role: '灾情研判与任务调度', status: 'active' },
      { id: 'flood-video-model', productCode: 'flood-video-interpretation', productName: '视频解译大模型', productType: 'model', source: 'partner', role: '水位、淹没区和险情识别', status: 'active' },
      { id: 'flood-data-platform', productCode: 'disaster-data-platform', productName: '数据管理平台', productType: 'data', source: 'self', role: '遥感、视频和事件数据沉淀', status: 'active' },
      { id: 'flood-report-agent', productCode: 'report-author-agent', productName: '报告编制智能体', productType: 'agent', source: 'self', role: '巡检报告与处置简报生成', status: 'active' },
    ],
    tiers: [
      { tierCode: 'free', tierName: 'Free', summary: '1 台无人机，1 路视频解译，不含报告编制', status: 'active', isPublic: true },
      { tierCode: 'pro', tierName: 'Pro', summary: '50 台无人机，50 路视频解译，报告编制 100 万字/年', status: 'active', isPublic: true },
      { tierCode: 'enterprise', tierName: 'Enterprise', summary: '专属资源、合同约定配额和现场交付服务', status: 'active', isPublic: true },
    ],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-28T00:00:00.000Z',
  },
  {
    id: 'solution-smart-legal',
    solutionCode: 'smart-legal',
    solutionName: '智慧法务',
    description: '面向企业法务、园区合规和政务法制场景，组合知识库、法务智能体、合同审查和报告编制能力。',
    industry: '企业服务 / 法务合规',
    scenario: '智慧法务',
    customerSegment: '集团法务、园区企业服务、政务法制部门',
    status: 'active',
    visibility: 'public',
    ownerTeam: '企业服务方案组',
    subscriptionCount: 18,
    activeTenantCount: 15,
    monthlyRevenue: 86000,
    tags: ['知识库', '合同审查', '报告编制'],
    products: [
      { id: 'legal-kb-platform', productCode: 'legal-knowledge-base', productName: '知识库平台', productType: 'platform', source: 'self', role: '法规、合同和案例知识沉淀', status: 'active' },
      { id: 'legal-agent', productCode: 'digital-legal', productName: '法务智能体', productType: 'agent', source: 'self', role: '法律问答、合规检索和材料生成', status: 'active' },
      { id: 'legal-contract-agent', productCode: 'contract-review', productName: '合同审核智能体', productType: 'agent', source: 'self', role: '合同条款抽取与风险提示', status: 'active' },
      { id: 'legal-report-agent', productCode: 'report-author-agent', productName: '报告编制智能体', productType: 'agent', source: 'self', role: '法务报告、合规报告生成', status: 'active' },
      { id: 'legal-search-model', productCode: 'legal-retrieval-model', productName: '法规检索模型', productType: 'model', source: 'partner', role: '法规语义检索与相似案例匹配', status: 'active' },
    ],
    tiers: [
      { tierCode: 'free', tierName: 'Free', summary: '100 万字报告编制，基础知识库存储空间', status: 'active', isPublic: true },
      { tierCode: 'pro', tierName: 'Pro', summary: '1000 万字报告编制，高级合同审查和扩展存储空间', status: 'active', isPublic: true },
      { tierCode: 'enterprise', tierName: 'Enterprise', summary: '专属知识库、私有模型接入和法务交付服务', status: 'active', isPublic: true },
    ],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-27T00:00:00.000Z',
  },
  {
    id: 'solution-emergency-command',
    solutionCode: 'emergency-command',
    solutionName: '应急指挥协同',
    description: '面向城市级应急指挥中心的跨部门协同方案，覆盖态势研判、资源调度、预案匹配和处置复盘。',
    industry: '应急管理 / 城市治理',
    scenario: '应急指挥协同',
    customerSegment: '城市应急指挥中心、区县应急局',
    status: 'draft',
    visibility: 'internal',
    ownerTeam: '城市治理方案组',
    subscriptionCount: 3,
    activeTenantCount: 1,
    monthlyRevenue: 32000,
    tags: ['态势研判', '预案匹配', '协同调度'],
    products: [
      { id: 'emergency-command-agent', productCode: 'emergency-command', productName: '应急指挥智能体', productType: 'agent', source: 'self', role: '预案匹配、态势研判和指挥建议', status: 'active' },
      { id: 'emergency-ops-agent', productCode: 'operation-analysis', productName: '经营分析智能体', productType: 'agent', source: 'self', role: '事件复盘和指标归因', status: 'active' },
      { id: 'emergency-data-platform', productCode: 'event-data-platform', productName: '事件数据平台', productType: 'data', source: 'self', role: '事件、资源和处置过程数据沉淀', status: 'draft' },
      { id: 'emergency-map-service', productCode: 'gis-service', productName: '空间态势服务', productType: 'service', source: 'partner', role: '地图态势和空间分析能力', status: 'draft' },
    ],
    tiers: [
      { tierCode: 'free', tierName: 'Free', summary: '单部门试用，基础预案匹配和少量事件复盘', status: 'draft', isPublic: false },
      { tierCode: 'pro', tierName: 'Pro', summary: '多部门协同、资源调度和月度处置复盘', status: 'draft', isPublic: false },
      { tierCode: 'enterprise', tierName: 'Enterprise', summary: '城市级专属部署、联动接口和现场保障服务', status: 'draft', isPublic: false },
    ],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-26T00:00:00.000Z',
  },
];

const NEW_PRODUCT_DEFAULT_CODE = '__new_product_default__';
const TENANT_DEFAULT_CODE = '__tenant_default__';

export const productReleaseRecords: ProductReleaseRecord[] = [
  {
    id: '0bb203b6-7dfb-42d8-a6ad-920000000101',
    productCode: 'vxture-console-cn',
    productName: 'Vxture Console 国内版',
    productRegion: 'domestic',
    productStatus: 'active',
    releaseCode: 'console-cn-2026-q2',
    releaseName: '2026 Q2 商业发布',
    description: '面向国内租户的 console 平台智能助手与运营能力发布，版本等级由本发布定义。',
    releaseType: 'standard',
    versionLabels: ['基础版', '专业版', '企业版'],
    isFree: false,
    isPublic: true,
    isActive: true,
    prices: [
      { id: 'c211fef4-88ef-45cc-bfe4-940000000101', currency: 'CNY', price: 2999, originalPrice: 3999, periodType: 'monthly', periodValue: 1, isDefault: true, isActive: true },
      { id: 'c211fef4-88ef-45cc-bfe4-940000000102', currency: 'CNY', price: 29900, originalPrice: 39990, periodType: 'yearly', periodValue: 1, isDefault: false, isActive: true },
    ],
    features: [
      { code: 'release.versions', name: '发布版本', type: 'function', quotaValue: 3, isUnlimited: false, config: { labels: ['基础版', '专业版', '企业版'] } },
      { code: 'ai.business_agents', name: '智能体应用', type: 'function', quotaValue: 1, isUnlimited: false, config: { includedAgents: ['console-assistant'] } },
      { code: 'ai.token_metering', name: '租户模型用量监测', type: 'function', quotaValue: 1, isUnlimited: false, config: { period: 'monthly' } },
    ],
    allowedAgents: ['Console 平台智能助手'],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
  {
    id: '0bb203b6-7dfb-42d8-a6ad-920000000102',
    productCode: 'ruyinagent-cn',
    productName: 'Ruyin Agent 国内版',
    productRegion: 'domestic',
    productStatus: 'active',
    releaseCode: 'ruyinagent-cn-2026-q2',
    releaseName: '2026 Q2 对话验证发布',
    description: 'ruyinagent 国内版验证发布，先以对话智能体接入产品与模型授权链路。',
    releaseType: 'standard',
    versionLabels: ['基础版', '高级版', '定制版'],
    isFree: false,
    isPublic: true,
    isActive: true,
    prices: [
      { id: 'c211fef4-88ef-45cc-bfe4-940000000201', currency: 'CNY', price: 1999, originalPrice: 2999, periodType: 'monthly', periodValue: 1, isDefault: true, isActive: true },
      { id: 'c211fef4-88ef-45cc-bfe4-940000000202', currency: 'CNY', price: 19900, originalPrice: 29990, periodType: 'yearly', periodValue: 1, isDefault: false, isActive: true },
    ],
    features: [
      { code: 'release.versions', name: '发布版本', type: 'function', quotaValue: 3, isUnlimited: false, config: { labels: ['基础版', '高级版', '定制版'] } },
      { code: 'ai.business_agents', name: '智能体应用', type: 'function', quotaValue: 1, isUnlimited: false, config: { includedAgents: ['ruyinagent'] } },
      { code: 'ai.token_metering', name: '租户模型用量监测', type: 'function', quotaValue: 1, isUnlimited: false, config: { period: 'monthly' } },
    ],
    allowedAgents: ['Ruyin Agent'],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
  {
    id: '0bb203b6-7dfb-42d8-a6ad-920000000103',
    productCode: 'ruyinagent-intl',
    productName: 'Ruyin Agent 国际版',
    productRegion: 'international',
    productStatus: 'draft',
    releaseCode: 'ruyinagent-intl-2026-q2-preview',
    releaseName: '2026 Q2 Preview',
    description: 'ruyinagent 国际版预览发布；产品存在但模型策略尚未定义，默认不授权。',
    releaseType: 'standard',
    versionLabels: ['Standard', 'Pro'],
    isFree: false,
    isPublic: false,
    isActive: false,
    prices: [
      { id: 'c211fef4-88ef-45cc-bfe4-940000000301', currency: 'USD', price: 399, originalPrice: 499, periodType: 'monthly', periodValue: 1, isDefault: true, isActive: false },
    ],
    features: [
      { code: 'release.versions', name: '发布版本', type: 'function', quotaValue: 2, isUnlimited: false, config: { labels: ['Standard', 'Pro'] } },
      { code: 'ai.business_agents', name: '智能体应用', type: 'function', quotaValue: 1, isUnlimited: false, config: { includedAgents: ['ruyinagent'] } },
    ],
    allowedAgents: ['Ruyin Agent'],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
];

export const productPlanRecords = productReleaseRecords;

function releaseByCode(productCode: string) {
  return productReleaseRecords.find((release) => release.productCode === productCode);
}

function productPolicy(input: {
  id: string;
  productCode: string;
  agentId: string;
  agentCode: string;
  agentName: string;
  modelCode: string;
  quotaTokens: number;
  priority: number;
  note: string;
}): ProductModelPolicyRecord {
  const release = releaseByCode(input.productCode);

  return {
    id: input.id,
    scopeType: 'product',
    scopeCode: input.productCode,
    scopeName: release?.productName ?? input.productCode,
    isDefined: true,
    productCode: input.productCode,
    productName: release?.productName ?? input.productCode,
    productRegion: release?.productRegion ?? null,
    agentId: input.agentId,
    agentCode: input.agentCode,
    agentName: input.agentName,
    modelCode: input.modelCode,
    quotaTokens: input.quotaTokens,
    isUnlimited: false,
    priority: input.priority,
    isActive: true,
    cycle: 'monthly',
    note: input.note,
  };
}

export const productModelPolicyRecords: ProductModelPolicyRecord[] = [
  productPolicy({
    id: 'policy-product-console-cn-lite',
    productCode: 'vxture-console-cn',
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'doubao-seed-2-0-lite-260215',
    quotaTokens: 10000000,
    priority: 100,
    note: 'Console 国内版基础在线模型，按产品授权，不区分发布版本。',
  }),
  productPolicy({
    id: 'policy-product-console-cn-pro',
    productCode: 'vxture-console-cn',
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'doubao-seed-2-0-pro-260215',
    quotaTokens: 5000000,
    priority: 80,
    note: 'Console 国内版增强模型授权。',
  }),
  productPolicy({
    id: 'policy-product-ruyin-cn-lite',
    productCode: 'ruyinagent-cn',
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'doubao-seed-2-0-lite-260215',
    quotaTokens: 8000000,
    priority: 100,
    note: 'Ruyin Agent 国内版兜底对话模型。',
  }),
  productPolicy({
    id: 'policy-product-ruyin-cn-pro',
    productCode: 'ruyinagent-cn',
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'doubao-seed-2-0-pro-260215',
    quotaTokens: 6000000,
    priority: 80,
    note: 'Ruyin Agent 国内版增强对话模型。',
  }),
  productPolicy({
    id: 'policy-product-ruyin-cn-private',
    productCode: 'ruyinagent-cn',
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'private-qwen-72b',
    quotaTokens: 0,
    priority: 40,
    note: '自建模型接入位已授权但配额为 0，交付后再开通额度。',
  }),
  {
    id: 'policy-default-new-product',
    scopeType: 'new_product_default',
    scopeCode: NEW_PRODUCT_DEFAULT_CODE,
    scopeName: '新产品授权策略',
    isDefined: false,
    productCode: NEW_PRODUCT_DEFAULT_CODE,
    productName: '新产品默认',
    productRegion: null,
    agentId: null,
    agentCode: null,
    agentName: '全部智能体',
    modelCode: null,
    quotaTokens: 0,
    isUnlimited: false,
    priority: 999,
    isActive: false,
    cycle: 'monthly',
    note: '未定义时默认不授权，新产品上线前需要补充产品级策略。',
  },
  {
    id: 'policy-default-tenant',
    scopeType: 'tenant_default',
    scopeCode: TENANT_DEFAULT_CODE,
    scopeName: '按租户授权策略',
    isDefined: false,
    productCode: TENANT_DEFAULT_CODE,
    productName: '租户默认',
    productRegion: null,
    agentId: null,
    agentCode: null,
    agentName: '全部智能体',
    modelCode: null,
    quotaTokens: 0,
    isUnlimited: false,
    priority: 1000,
    isActive: false,
    cycle: 'monthly',
    note: '未定义租户覆盖时回落到产品策略；产品策略也未定义时默认不授权。',
  },
  {
    id: 'policy-undefined-ruyinagent-intl',
    scopeType: 'product',
    scopeCode: 'ruyinagent-intl',
    scopeName: 'Ruyin Agent 国际版',
    isDefined: false,
    productCode: 'ruyinagent-intl',
    productName: 'Ruyin Agent 国际版',
    productRegion: 'international',
    agentId: null,
    agentCode: null,
    agentName: '全部智能体',
    modelCode: null,
    quotaTokens: 0,
    isUnlimited: false,
    priority: 999,
    isActive: false,
    cycle: 'monthly',
    note: '产品已发布但模型策略未定义，默认不授权。',
  },
];

export const tenantOperationRecords: TenantOperationRecord[] = [
  {
    id: 'tenant_demo',
    tenantCode: 'demo',
    tenantName: 'Vxture Demo Tenant',
    displayName: 'Vxture 演示租户',
    tenantType: 'company',
    status: 'active',
    verifiedStatus: 'verified',
    riskLevel: 'normal',
    region: '中国 / 上海',
    industry: 'AI 平台服务',
    scale: '100-300 人',
    ownerName: 'Lin Chen',
    ownerEmail: 'lin.chen@vxture.ai',
    contactName: 'Mika Zhou',
    contactPhone: '13800001002',
    createdAt: '2026-01-08T08:00:00.000Z',
    lastActiveAt: '2026-04-27T08:20:00.000Z',
    memberCount: 128,
    activeMemberCount: 96,
    adminCount: 5,
    subscriptionCount: 2,
    productCount: 2,
    monthlyRevenue: 42900,
    monthlyCost: 11800,
    grossMarginRate: 72,
    tokenUsed: 18400000,
    tokenQuota: 25000000,
    ticketOpenCount: 2,
    satisfaction: 4.8,
    sla: '99.96%',
    tags: ['重点客户', '模型策略已定义'],
    notes: '演示租户承担 console assistant 与 ruyinagent 的联调验证。',
    members: [
      { id: 'tm_demo_01', accountCode: 'acct-demo-lin', name: 'Lin Chen', email: 'lin.chen@vxture.ai', role: 'Owner', status: 'active', registeredAt: '2026-01-08T08:20:00.000Z', activatedAt: '2026-01-08T08:32:00.000Z', lastActiveAt: '2026-04-27T08:20:00.000Z', lastActiveIp: '101.33.12.18' },
      { id: 'tm_demo_02', accountCode: 'acct-demo-mika', name: 'Mika Zhou', email: 'mika.zhou@vxture.ai', role: 'Billing Admin', status: 'active', registeredAt: '2026-01-09T02:10:00.000Z', activatedAt: '2026-01-09T03:12:00.000Z', lastActiveAt: '2026-04-27T07:12:00.000Z', lastActiveIp: '111.206.145.7' },
      { id: 'tm_demo_03', accountCode: 'acct-demo-jun', name: 'Jun Park', email: 'jun.park@vxture.ai', role: 'Workspace Admin', status: 'invited', registeredAt: '2026-04-26T11:40:00.000Z', activatedAt: null, lastActiveAt: '2026-04-26T11:40:00.000Z', lastActiveIp: null },
      { id: 'tm_demo_04', accountCode: 'acct-demo-ava', name: 'Ava Song', email: 'ava.song@vxture.ai', role: 'Analyst', status: 'suspended', registeredAt: '2026-02-02T09:00:00.000Z', activatedAt: '2026-02-02T10:04:00.000Z', lastActiveAt: '2026-04-12T09:00:00.000Z', lastActiveIp: '112.93.64.21' },
    ],
    subscriptions: [
      {
        id: 'sub_demo_console',
        productName: 'Vxture Console 国内版',
        releaseName: '2026 Q2 商业发布',
        planName: '企业版',
        status: 'active',
        seats: 120,
        monthlyRevenue: 29900,
        startedAt: '2026-01-08T08:00:00.000Z',
        renewsAt: '2026-05-18T08:00:00.000Z',
      },
      {
        id: 'sub_demo_ruyin',
        productName: 'Ruyin Agent 国内版',
        releaseName: '2026 Q2 对话验证发布',
        planName: '高级版',
        status: 'active',
        seats: 60,
        monthlyRevenue: 13000,
        startedAt: '2026-04-01T08:00:00.000Z',
        renewsAt: '2026-05-01T08:00:00.000Z',
      },
    ],
    usage: [
      { code: 'tokens', label: '模型 Token', used: 18400000, quota: 25000000, unit: 'tokens', trend: '+8%', status: 'normal' },
      { code: 'members', label: '成员席位', used: 128, quota: 180, unit: 'seats', trend: '+12', status: 'normal' },
      { code: 'storage', label: '知识库容量', used: 4200, quota: 6000, unit: 'GB', trend: '+320', status: 'normal' },
    ],
    modelPolicies: [
      { id: 'tmp_demo_console_lite', agentName: 'Console 平台智能助手', productName: 'Vxture Console 国内版', modelCode: 'doubao-seed-2-0-lite-260215', quotaTokens: 10000000, usedTokens: 8200000, state: 'effective', source: 'product' },
      { id: 'tmp_demo_console_pro', agentName: 'Console 平台智能助手', productName: 'Vxture Console 国内版', modelCode: 'doubao-seed-2-0-pro-260215', quotaTokens: 5000000, usedTokens: 3100000, state: 'effective', source: 'product' },
      { id: 'tmp_demo_ruyin_lite', agentName: 'Ruyin Agent', productName: 'Ruyin Agent 国内版', modelCode: 'doubao-seed-2-0-lite-260215', quotaTokens: 8000000, usedTokens: 7100000, state: 'effective', source: 'product' },
    ],
    auditEvents: [
      { id: 'audit_demo_01', action: '更新模型策略', actor: 'superadmin', at: '2026-04-26T10:22:00.000Z', result: 'success' },
      { id: 'audit_demo_02', action: '成员状态调整', actor: 'ops_admin', at: '2026-04-24T13:10:00.000Z', result: 'warning' },
      { id: 'audit_demo_03', action: '订阅续费确认', actor: 'billing_admin', at: '2026-04-18T09:00:00.000Z', result: 'success' },
    ],
    tickets: [
      { id: 'TCK-1021', title: 'Console assistant 回复延迟波动', status: 'processing', priority: 'p1', updatedAt: '2026-04-27T07:42:00.000Z' },
      { id: 'TCK-1014', title: '补充 ruyinagent 对话模板', status: 'open', priority: 'p2', updatedAt: '2026-04-26T15:30:00.000Z' },
    ],
  },
  {
    id: 'tenant_haicheng',
    tenantCode: 'haicheng',
    tenantName: 'Haicheng Digital Tech',
    displayName: '海澄数字科技',
    tenantType: 'company',
    status: 'active',
    verifiedStatus: 'pending',
    riskLevel: 'follow_up',
    region: '中国 / 浙江',
    industry: '制造业数字化',
    scale: '300-1000 人',
    ownerName: 'Zoe Wang',
    ownerEmail: 'zoe.wang@haicheng.example',
    contactName: 'Zoe Wang',
    contactPhone: '13900002001',
    createdAt: '2026-02-14T08:00:00.000Z',
    lastActiveAt: '2026-04-27T06:12:00.000Z',
    memberCount: 86,
    activeMemberCount: 51,
    adminCount: 3,
    subscriptionCount: 1,
    productCount: 1,
    monthlyRevenue: 29900,
    monthlyCost: 9600,
    grossMarginRate: 68,
    tokenUsed: 22100000,
    tokenQuota: 24000000,
    ticketOpenCount: 3,
    satisfaction: 4.3,
    sla: '99.82%',
    tags: ['认证待审', '计量接近阈值'],
    notes: '制造业知识库导入量较高，需要观察本周 Token 峰值。',
    members: [
      { id: 'tm_hc_01', accountCode: 'acct-hc-zoe', name: 'Zoe Wang', email: 'zoe.wang@haicheng.example', role: 'Owner', status: 'active', registeredAt: '2026-02-14T08:20:00.000Z', activatedAt: '2026-02-14T08:45:00.000Z', lastActiveAt: '2026-04-27T06:12:00.000Z', lastActiveIp: '115.236.80.12' },
      { id: 'tm_hc_02', accountCode: 'acct-hc-han', name: 'Han Li', email: 'han.li@haicheng.example', role: 'Admin', status: 'active', registeredAt: '2026-02-18T08:21:00.000Z', activatedAt: '2026-02-18T09:10:00.000Z', lastActiveAt: '2026-04-26T18:40:00.000Z', lastActiveIp: '221.12.46.18' },
      { id: 'tm_hc_03', accountCode: 'acct-hc-qian', name: 'Qian Wu', email: 'qian.wu@haicheng.example', role: 'Member', status: 'active', registeredAt: '2026-03-01T09:02:00.000Z', activatedAt: '2026-03-01T09:24:00.000Z', lastActiveAt: '2026-04-25T11:02:00.000Z', lastActiveIp: '183.129.15.49' },
    ],
    subscriptions: [
      {
        id: 'sub_hc_console',
        productName: 'Vxture Console 国内版',
        releaseName: '2026 Q2 商业发布',
        planName: '专业版',
        status: 'active',
        seats: 100,
        monthlyRevenue: 29900,
        startedAt: '2026-02-14T08:00:00.000Z',
        renewsAt: '2026-05-14T08:00:00.000Z',
      },
    ],
    usage: [
      { code: 'tokens', label: '模型 Token', used: 22100000, quota: 24000000, unit: 'tokens', trend: '+19%', status: 'warning' },
      { code: 'members', label: '成员席位', used: 86, quota: 100, unit: 'seats', trend: '+9', status: 'normal' },
      { code: 'storage', label: '知识库容量', used: 5600, quota: 6000, unit: 'GB', trend: '+740', status: 'warning' },
    ],
    modelPolicies: [
      { id: 'tmp_hc_console_lite', agentName: 'Console 平台智能助手', productName: 'Vxture Console 国内版', modelCode: 'doubao-seed-2-0-lite-260215', quotaTokens: 10000000, usedTokens: 9800000, state: 'limited', source: 'product' },
      { id: 'tmp_hc_console_pro', agentName: 'Console 平台智能助手', productName: 'Vxture Console 国内版', modelCode: 'doubao-seed-2-0-pro-260215', quotaTokens: 5000000, usedTokens: 4600000, state: 'limited', source: 'product' },
    ],
    auditEvents: [
      { id: 'audit_hc_01', action: '认证材料提交', actor: 'zoe.wang', at: '2026-04-26T14:18:00.000Z', result: 'warning' },
      { id: 'audit_hc_02', action: '用量阈值告警', actor: 'system', at: '2026-04-26T03:00:00.000Z', result: 'warning' },
      { id: 'audit_hc_03', action: '新增成员', actor: 'han.li', at: '2026-04-22T08:21:00.000Z', result: 'success' },
    ],
    tickets: [
      { id: 'TCK-1040', title: '组织认证资料待复核', status: 'open', priority: 'p1', updatedAt: '2026-04-27T06:30:00.000Z' },
      { id: 'TCK-1038', title: '知识库容量接近上限', status: 'processing', priority: 'p2', updatedAt: '2026-04-26T16:08:00.000Z' },
      { id: 'TCK-1031', title: '月度用量报表口径确认', status: 'blocked', priority: 'p2', updatedAt: '2026-04-25T12:00:00.000Z' },
    ],
  },
  {
    id: 'tenant_ruyin',
    tenantCode: 'ruyin-lab',
    tenantName: 'Ruyin Lab',
    displayName: '如因智能实验室',
    tenantType: 'company',
    status: 'trial',
    verifiedStatus: 'unverified',
    riskLevel: 'normal',
    region: '中国 / 北京',
    industry: '智能体应用',
    scale: '30-100 人',
    ownerName: 'Ray Yin',
    ownerEmail: 'ray.yin@ruyin.example',
    contactName: 'Ray Yin',
    contactPhone: '13700003001',
    createdAt: '2026-04-11T08:00:00.000Z',
    lastActiveAt: '2026-04-27T04:05:00.000Z',
    memberCount: 24,
    activeMemberCount: 19,
    adminCount: 2,
    subscriptionCount: 1,
    productCount: 1,
    monthlyRevenue: 19900,
    monthlyCost: 4200,
    grossMarginRate: 79,
    tokenUsed: 6200000,
    tokenQuota: 14000000,
    ticketOpenCount: 1,
    satisfaction: 4.6,
    sla: '99.91%',
    tags: ['试用期', 'Ruyin Agent'],
    notes: 'ruyinagent 对话验证租户，优先观察智能体用量与留存。',
    members: [
      { id: 'tm_ry_01', accountCode: 'acct-ry-ray', name: 'Ray Yin', email: 'ray.yin@ruyin.example', role: 'Owner', status: 'active', registeredAt: '2026-04-11T08:00:00.000Z', activatedAt: '2026-04-11T08:06:00.000Z', lastActiveAt: '2026-04-27T04:05:00.000Z', lastActiveIp: '123.125.71.38' },
      { id: 'tm_ry_02', accountCode: 'acct-ry-nora', name: 'Nora Liu', email: 'nora.liu@ruyin.example', role: 'Admin', status: 'active', registeredAt: '2026-04-12T09:10:00.000Z', activatedAt: '2026-04-12T09:28:00.000Z', lastActiveAt: '2026-04-26T17:16:00.000Z', lastActiveIp: '36.112.24.19' },
      { id: 'tm_ry_03', accountCode: 'acct-ry-kane', name: 'Kane Zhao', email: 'kane.zhao@ruyin.example', role: 'Member', status: 'invited', registeredAt: '2026-04-25T08:10:00.000Z', activatedAt: null, lastActiveAt: '2026-04-25T08:10:00.000Z', lastActiveIp: null },
    ],
    subscriptions: [
      {
        id: 'sub_ry_ruyin',
        productName: 'Ruyin Agent 国内版',
        releaseName: '2026 Q2 对话验证发布',
        planName: '高级版',
        status: 'trial',
        seats: 30,
        monthlyRevenue: 19900,
        startedAt: '2026-04-11T08:00:00.000Z',
        renewsAt: '2026-05-11T08:00:00.000Z',
      },
    ],
    usage: [
      { code: 'tokens', label: '模型 Token', used: 6200000, quota: 14000000, unit: 'tokens', trend: '+11%', status: 'normal' },
      { code: 'members', label: '成员席位', used: 24, quota: 30, unit: 'seats', trend: '+4', status: 'normal' },
      { code: 'storage', label: '知识库容量', used: 1100, quota: 3000, unit: 'GB', trend: '+160', status: 'normal' },
    ],
    modelPolicies: [
      { id: 'tmp_ry_ruyin_lite', agentName: 'Ruyin Agent', productName: 'Ruyin Agent 国内版', modelCode: 'doubao-seed-2-0-lite-260215', quotaTokens: 8000000, usedTokens: 4100000, state: 'effective', source: 'product' },
      { id: 'tmp_ry_ruyin_private', agentName: 'Ruyin Agent', productName: 'Ruyin Agent 国内版', modelCode: 'private-qwen-72b', quotaTokens: 0, usedTokens: 0, state: 'disabled', source: 'product' },
    ],
    auditEvents: [
      { id: 'audit_ry_01', action: '试用租户创建', actor: 'superadmin', at: '2026-04-11T08:00:00.000Z', result: 'success' },
      { id: 'audit_ry_02', action: 'Ruyin Agent 开通', actor: 'ops_admin', at: '2026-04-11T08:30:00.000Z', result: 'success' },
    ],
    tickets: [
      { id: 'TCK-1028', title: '试用转正式报价确认', status: 'open', priority: 'p3', updatedAt: '2026-04-26T09:20:00.000Z' },
    ],
  },
  {
    id: 'tenant_northstar',
    tenantCode: 'northstar',
    tenantName: 'Northstar Emergency',
    displayName: '北极星应急平台',
    tenantType: 'company',
    status: 'suspended',
    verifiedStatus: 'verified',
    riskLevel: 'high',
    region: '中国 / 四川',
    industry: '应急管理',
    scale: '1000+ 人',
    ownerName: 'Ming Gao',
    ownerEmail: 'ming.gao@northstar.example',
    contactName: 'Ming Gao',
    contactPhone: '13600004001',
    createdAt: '2025-11-20T08:00:00.000Z',
    lastActiveAt: '2026-04-20T10:00:00.000Z',
    memberCount: 312,
    activeMemberCount: 0,
    adminCount: 8,
    subscriptionCount: 2,
    productCount: 2,
    monthlyRevenue: 0,
    monthlyCost: 2200,
    grossMarginRate: -100,
    tokenUsed: 0,
    tokenQuota: 0,
    ticketOpenCount: 4,
    satisfaction: 3.2,
    sla: '98.40%',
    tags: ['服务暂停', '待人工复核'],
    notes: '因合同与安全复核暂停服务，需运营与法务共同确认恢复条件。',
    members: [
      { id: 'tm_ns_01', accountCode: 'acct-ns-ming', name: 'Ming Gao', email: 'ming.gao@northstar.example', role: 'Owner', status: 'suspended', registeredAt: '2025-11-20T08:00:00.000Z', activatedAt: '2025-11-20T08:18:00.000Z', lastActiveAt: '2026-04-20T10:00:00.000Z', lastActiveIp: '171.221.32.8' },
      { id: 'tm_ns_02', accountCode: 'acct-ns-lei', name: 'Lei Tang', email: 'lei.tang@northstar.example', role: 'Admin', status: 'suspended', registeredAt: '2025-11-22T07:30:00.000Z', activatedAt: '2025-11-22T07:56:00.000Z', lastActiveAt: '2026-04-19T16:00:00.000Z', lastActiveIp: '182.150.21.18' },
    ],
    subscriptions: [
      {
        id: 'sub_ns_console',
        productName: 'Vxture Console 国内版',
        releaseName: '2026 Q2 商业发布',
        planName: '定制版',
        status: 'past_due',
        seats: 300,
        monthlyRevenue: 0,
        startedAt: '2025-11-20T08:00:00.000Z',
        renewsAt: '2026-04-20T08:00:00.000Z',
      },
      {
        id: 'sub_ns_ruyin',
        productName: 'Ruyin Agent 国内版',
        releaseName: '2026 Q2 对话验证发布',
        planName: '定制版',
        status: 'cancelled',
        seats: 300,
        monthlyRevenue: 0,
        startedAt: '2026-01-01T08:00:00.000Z',
        renewsAt: null,
      },
    ],
    usage: [
      { code: 'tokens', label: '模型 Token', used: 0, quota: 0, unit: 'tokens', trend: '-100%', status: 'danger' },
      { code: 'members', label: '成员席位', used: 312, quota: 300, unit: 'seats', trend: '超额', status: 'danger' },
      { code: 'storage', label: '知识库容量', used: 7800, quota: 8000, unit: 'GB', trend: '冻结', status: 'warning' },
    ],
    modelPolicies: [
      { id: 'tmp_ns_console_lite', agentName: 'Console 平台智能助手', productName: 'Vxture Console 国内版', modelCode: 'doubao-seed-2-0-lite-260215', quotaTokens: 0, usedTokens: 0, state: 'disabled', source: 'tenant' },
      { id: 'tmp_ns_ruyin_private', agentName: 'Ruyin Agent', productName: 'Ruyin Agent 国内版', modelCode: 'private-qwen-72b', quotaTokens: 0, usedTokens: 0, state: 'disabled', source: 'tenant' },
    ],
    auditEvents: [
      { id: 'audit_ns_01', action: '租户暂停', actor: 'superadmin', at: '2026-04-20T10:10:00.000Z', result: 'danger' },
      { id: 'audit_ns_02', action: '账期逾期', actor: 'system', at: '2026-04-20T08:00:00.000Z', result: 'warning' },
      { id: 'audit_ns_03', action: '安全复核创建', actor: 'security_admin', at: '2026-04-19T09:30:00.000Z', result: 'warning' },
    ],
    tickets: [
      { id: 'TCK-1052', title: '恢复服务条件确认', status: 'blocked', priority: 'p0', updatedAt: '2026-04-27T02:30:00.000Z' },
      { id: 'TCK-1049', title: '逾期账单人工复核', status: 'processing', priority: 'p1', updatedAt: '2026-04-26T10:10:00.000Z' },
      { id: 'TCK-1044', title: '客户安全材料补充', status: 'open', priority: 'p1', updatedAt: '2026-04-25T15:00:00.000Z' },
      { id: 'TCK-1035', title: '知识库冻结确认', status: 'blocked', priority: 'p2', updatedAt: '2026-04-24T18:00:00.000Z' },
    ],
  },
  {
    id: 'tenant_personal_chen',
    tenantCode: 'chen-personal',
    tenantName: 'Chen Personal Workspace',
    displayName: '陈一的个人租户',
    tenantType: 'individual',
    status: 'active',
    verifiedStatus: 'verified',
    riskLevel: 'normal',
    region: '中国 / 广东',
    industry: '个人开发者',
    scale: '个人',
    ownerName: 'Yi Chen',
    ownerEmail: 'yi.chen@example.com',
    contactName: 'Yi Chen',
    contactPhone: '13500005001',
    createdAt: '2026-03-02T08:00:00.000Z',
    lastActiveAt: '2026-04-26T21:14:00.000Z',
    memberCount: 1,
    activeMemberCount: 1,
    adminCount: 1,
    subscriptionCount: 1,
    productCount: 1,
    monthlyRevenue: 1999,
    monthlyCost: 260,
    grossMarginRate: 87,
    tokenUsed: 720000,
    tokenQuota: 3000000,
    ticketOpenCount: 0,
    satisfaction: 4.9,
    sla: '99.98%',
    tags: ['个人租户', '轻量使用'],
    notes: '个人租户仅保留运营观察字段，与企业组织认证分开处理。',
    members: [
      { id: 'tm_pc_01', accountCode: 'acct-pc-yi', name: 'Yi Chen', email: 'yi.chen@example.com', role: 'Owner', status: 'active', registeredAt: '2026-03-02T08:00:00.000Z', activatedAt: '2026-03-02T08:12:00.000Z', lastActiveAt: '2026-04-26T21:14:00.000Z', lastActiveIp: '119.29.62.12' },
    ],
    subscriptions: [
      {
        id: 'sub_pc_ruyin',
        productName: 'Ruyin Agent 国内版',
        releaseName: '2026 Q2 对话验证发布',
        planName: '基础版',
        status: 'active',
        seats: 1,
        monthlyRevenue: 1999,
        startedAt: '2026-03-02T08:00:00.000Z',
        renewsAt: '2026-05-02T08:00:00.000Z',
      },
    ],
    usage: [
      { code: 'tokens', label: '模型 Token', used: 720000, quota: 3000000, unit: 'tokens', trend: '+3%', status: 'normal' },
      { code: 'members', label: '成员席位', used: 1, quota: 1, unit: 'seats', trend: '稳定', status: 'normal' },
      { code: 'storage', label: '知识库容量', used: 120, quota: 500, unit: 'GB', trend: '+12', status: 'normal' },
    ],
    modelPolicies: [
      { id: 'tmp_pc_ruyin_lite', agentName: 'Ruyin Agent', productName: 'Ruyin Agent 国内版', modelCode: 'doubao-seed-2-0-lite-260215', quotaTokens: 8000000, usedTokens: 720000, state: 'effective', source: 'product' },
    ],
    auditEvents: [
      { id: 'audit_pc_01', action: '订阅续费', actor: 'yi.chen', at: '2026-04-02T08:00:00.000Z', result: 'success' },
      { id: 'audit_pc_02', action: '个人认证通过', actor: 'ops_admin', at: '2026-03-03T09:00:00.000Z', result: 'success' },
    ],
    tickets: [],
  },
];

export const accountOperationRecords: AccountOperationRecord[] = tenantOperationRecords.flatMap((tenant, tenantIndex) =>
  tenant.members.map((member, memberIndex) => {
    const isPrimaryOwner = member.role.toLowerCase().includes('owner');
    const status: AccountOperationRecord['status'] =
      member.status === 'active' ? 'active' : member.status === 'invited' ? 'invited' : tenant.status === 'suspended' ? 'disabled' : 'locked';

    return {
      id: member.id,
      accountCode: member.accountCode ?? member.email.split('@')[0] ?? member.id,
      displayName: member.name,
      email: member.email,
      phone: member.lastActiveIp ? `13${tenantIndex + 5}${String(memberIndex + 10000000).slice(0, 8)}` : null,
      status,
      primaryTenantId: tenant.id,
      primaryTenantCode: tenant.tenantCode,
      primaryTenantName: tenant.displayName,
      primaryTenantType: tenant.tenantType,
      role: member.role,
      tenantCount: 1,
      registeredAt: member.registeredAt ?? tenant.createdAt,
      activatedAt: member.activatedAt ?? null,
      lastActiveAt: member.lastActiveAt,
      lastActiveIp: member.lastActiveIp ?? null,
      lastActiveLocation: member.lastActiveIp ? resolveIpLocation(member.lastActiveIp) : '未激活',
      loginCount30d: member.status === 'active' ? 28 + tenantIndex * 3 + memberIndex * 5 : member.status === 'invited' ? 0 : 3,
      tenantBindings: [
        {
          tenantId: tenant.id,
          tenantCode: tenant.tenantCode,
          tenantName: tenant.displayName,
          tenantType: tenant.tenantType,
          role: member.role,
          isPrimaryOwner,
        },
      ],
    };
  }),
);

export const legacyProductModelPolicyRecords = [
  {
    id: 'policy-starter-console-lite',
    planCode: 'starter',
    planName: '入门版',
    planLevel: 10,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'doubao-seed-2-0-lite-260215',
    quotaTokens: 1000000,
    isUnlimited: false,
    priority: 100,
    isActive: true,
    cycle: 'monthly',
    note: '入门版默认对话模型。',
  },
  {
    id: 'policy-starter-console-pro',
    planCode: 'starter',
    planName: '入门版',
    planLevel: 10,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'doubao-seed-2-0-pro-260215',
    quotaTokens: 0,
    isUnlimited: false,
    priority: 200,
    isActive: true,
    cycle: 'monthly',
    note: '已授权但配额为 0，用于套餐升级提示。',
  },
  {
    id: 'policy-starter-ruyin-lite',
    planCode: 'starter',
    planName: '入门版',
    planLevel: 10,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'doubao-seed-2-0-lite-260215',
    quotaTokens: 0,
    isUnlimited: false,
    priority: 100,
    isActive: true,
    cycle: 'monthly',
    note: '验证期先预置授权，默认配额为 0。',
  },
  {
    id: 'policy-growth-console-lite',
    planCode: 'growth',
    planName: '专业版',
    planLevel: 20,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'doubao-seed-2-0-lite-260215',
    quotaTokens: 5000000,
    isUnlimited: false,
    priority: 100,
    isActive: true,
    cycle: 'monthly',
    note: '专业版兜底模型。',
  },
  {
    id: 'policy-growth-console-pro',
    planCode: 'growth',
    planName: '专业版',
    planLevel: 20,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'doubao-seed-2-0-pro-260215',
    quotaTokens: 10000000,
    isUnlimited: false,
    priority: 50,
    isActive: true,
    cycle: 'monthly',
    note: '专业版优先模型。',
  },
  {
    id: 'policy-growth-ruyin-lite',
    planCode: 'growth',
    planName: '专业版',
    planLevel: 20,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'doubao-seed-2-0-lite-260215',
    quotaTokens: 5000000,
    isUnlimited: false,
    priority: 100,
    isActive: true,
    cycle: 'monthly',
    note: 'Ruyin Agent 专业版兜底模型。',
  },
  {
    id: 'policy-growth-ruyin-pro',
    planCode: 'growth',
    planName: '专业版',
    planLevel: 20,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'doubao-seed-2-0-pro-260215',
    quotaTokens: 5000000,
    isUnlimited: false,
    priority: 60,
    isActive: true,
    cycle: 'monthly',
    note: 'Ruyin Agent 专业版优先模型。',
  },
  {
    id: 'policy-enterprise-console-pro',
    planCode: 'enterprise',
    planName: '企业版',
    planLevel: 30,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'doubao-seed-2-0-pro-260215',
    quotaTokens: 30000000,
    isUnlimited: false,
    priority: 50,
    isActive: true,
    cycle: 'monthly',
    note: '企业版主力在线模型。',
  },
  {
    id: 'policy-enterprise-console-claude',
    planCode: 'enterprise',
    planName: '企业版',
    planLevel: 30,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000005',
    agentCode: 'console-assistant',
    agentName: 'Console 平台智能助手',
    modelCode: 'claude-sonnet-4-20250514',
    quotaTokens: 20000000,
    isUnlimited: false,
    priority: 30,
    isActive: true,
    cycle: 'monthly',
    note: '企业版复杂推理模型。',
  },
  {
    id: 'policy-enterprise-ruyin-pro',
    planCode: 'enterprise',
    planName: '企业版',
    planLevel: 30,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'doubao-seed-2-0-pro-260215',
    quotaTokens: 30000000,
    isUnlimited: false,
    priority: 50,
    isActive: true,
    cycle: 'monthly',
    note: 'Ruyin Agent 企业版主力模型。',
  },
  {
    id: 'policy-enterprise-ruyin-claude',
    planCode: 'enterprise',
    planName: '企业版',
    planLevel: 30,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'claude-sonnet-4-20250514',
    quotaTokens: 20000000,
    isUnlimited: false,
    priority: 30,
    isActive: true,
    cycle: 'monthly',
    note: 'Ruyin Agent 企业版复杂推理模型。',
  },
  {
    id: 'policy-enterprise-ruyin-private',
    planCode: 'enterprise',
    planName: '企业版',
    planLevel: 30,
    agentId: '2b3158c4-fd0a-4ffc-a5c6-910000000006',
    agentCode: 'ruyinagent',
    agentName: 'Ruyin Agent',
    modelCode: 'private-qwen-72b',
    quotaTokens: 0,
    isUnlimited: false,
    priority: 20,
    isActive: true,
    cycle: 'monthly',
    note: '自建模型位已预留，客户交付后再开配额。',
  },
];

export const legacyProductPlanRecords = [
  {
    id: '0bb203b6-7dfb-42d8-a6ad-920000000001',
    planCode: 'starter',
    planName: '入门版',
    description: '适合个人或小团队试用，包含基础在线模型额度。',
    planType: 'normal',
    level: 10,
    isFree: true,
    isPublic: true,
    isActive: true,
    prices: [
      { id: 'c211fef4-88ef-45cc-bfe4-940000000001', currency: 'CNY', price: 0, originalPrice: 0, periodType: 'monthly', periodValue: 1, isDefault: true, isActive: true },
    ],
    features: [
      { code: 'ai.tokens', name: '模型调用额度', type: 'quota', quotaValue: 1000000, isUnlimited: false, config: null },
      { code: 'ai.online_models', name: '在线模型服务', type: 'function', quotaValue: 1, isUnlimited: false, config: null },
      { code: 'ai.business_agents', name: '智能体应用', type: 'function', quotaValue: 2, isUnlimited: false, config: { includedAgents: ['console-assistant', 'ruyinagent'], modelPolicyMode: 'agent-plan-quota' } },
    ],
    allowedAgents: ['Console 平台智能助手', 'Ruyin Agent'],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
  {
    id: '0bb203b6-7dfb-42d8-a6ad-920000000002',
    planCode: 'growth',
    planName: '专业版',
    description: '适合组织客户使用通用业务智能体和在线模型。',
    planType: 'normal',
    level: 20,
    isFree: false,
    isPublic: true,
    isActive: true,
    prices: [
      { id: 'c211fef4-88ef-45cc-bfe4-940000000002', currency: 'CNY', price: 2999, originalPrice: 3999, periodType: 'monthly', periodValue: 1, isDefault: true, isActive: true },
      { id: 'c211fef4-88ef-45cc-bfe4-940000000003', currency: 'CNY', price: 29900, originalPrice: 39990, periodType: 'yearly', periodValue: 1, isDefault: false, isActive: true },
    ],
    features: [
      { code: 'ai.tokens', name: '模型调用额度', type: 'quota', quotaValue: 20000000, isUnlimited: false, config: null },
      { code: 'ai.online_models', name: '在线模型服务', type: 'function', quotaValue: 1, isUnlimited: false, config: null },
      { code: 'ai.business_agents', name: '智能体应用', type: 'function', quotaValue: 2, isUnlimited: false, config: { includedAgents: ['console-assistant', 'ruyinagent'], modelPolicyMode: 'agent-plan-quota' } },
    ],
    allowedAgents: ['Console 平台智能助手', 'Ruyin Agent'],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
  {
    id: '0bb203b6-7dfb-42d8-a6ad-920000000003',
    planCode: 'enterprise',
    planName: '企业版',
    description: '面向行业客户，支持高额度、自建模型接入和专属方案服务。',
    planType: 'normal',
    level: 30,
    isFree: false,
    isPublic: true,
    isActive: true,
    prices: [
      { id: 'c211fef4-88ef-45cc-bfe4-940000000004', currency: 'CNY', price: 9999, originalPrice: 12999, periodType: 'monthly', periodValue: 1, isDefault: true, isActive: true },
      { id: 'c211fef4-88ef-45cc-bfe4-940000000005', currency: 'CNY', price: 99900, originalPrice: 129990, periodType: 'yearly', periodValue: 1, isDefault: false, isActive: true },
    ],
    features: [
      { code: 'ai.tokens', name: '模型调用额度', type: 'quota', quotaValue: 100000000, isUnlimited: false, config: null },
      { code: 'ai.online_models', name: '在线模型服务', type: 'function', quotaValue: 1, isUnlimited: true, config: null },
      { code: 'ai.private_model', name: '自建模型接入', type: 'function', quotaValue: 1, isUnlimited: false, config: null },
      { code: 'ai.business_agents', name: '智能体应用', type: 'function', quotaValue: 2, isUnlimited: true, config: { includedAgents: ['console-assistant', 'ruyinagent'], modelPolicyMode: 'agent-plan-quota' } },
    ],
    allowedAgents: ['Console 平台智能助手', 'Ruyin Agent'],
    createdAt: '2026-04-25T00:00:00.000Z',
    updatedAt: '2026-04-25T00:00:00.000Z',
  },
];
