sonar.projectKey=6b309295f6500aba6b2a71a29ee27de77fa41583_vxture
sonar.organization=6b309295f6500aba6b2a71a29ee27de77fa41583


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=6b309295f6500aba6b2a71a29ee27de77fa41583_vxture
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
