// 颜色主题类型
export type SectionTheme = "light" | "dark" | "system";

// 颜色主键类型（主流语义色体系）
type ColorKey = "primary" | "secondary" | "info" | "success" | "warning" | "danger" | "gray";

// 单色板结构（主流语义字段，便于全局一致性和扩展）
export interface ColorMap {
  bgSection: string;         // 区块背景
  bgCard: string;            // 卡片背景
  textMain: string;          // 主标题
  textSub: string;           // 副标题
  textDesc: string;          // 描述/正文
  textButton: string;        // 按钮文字
  bgButton: string;          // 按钮背景
  bgButtonHover: string;     // 按钮悬停背景
  borderButton: string;      // 按钮边框
  iconMain: string;          // 主图标
  iconSecondary: string;     // 次图标
  tagBg: string;             // 标签背景
  tagText: string;           // 标签文字
  divider: string;           // 分割线
  dividerRight: string;      // 右分割线渐变
  dividerLeft: string;       // 左分割线渐变
  borderDecorative: string;  // 装饰性边框/渐变
}

// 主题色板结构
export type ThemeColorMap = Record<ColorKey, ColorMap>;

// 单独定义 light/dark 主题色板，避免变量提升问题
const LightColorMap: ThemeColorMap = {
  primary: {
    bgSection: "bg-gradient-to-b from-blue-50 to-white",
    bgCard: "bg-white",
    textMain: "text-blue-800",
    textSub: "text-blue-500",
    textDesc: "text-gray-500",
    textButton: "text-white",
    bgButton: "bg-blue-600",
    bgButtonHover: "hover:bg-blue-700",
    borderButton: "border-blue-600",
    iconMain: "text-blue-500",
    iconSecondary: "text-blue-300",
    tagBg: "bg-blue-50",
    tagText: "text-blue-600",
    divider: "bg-blue-100",
    dividerRight: "bg-gradient-to-r from-transparent to-blue-200",
    dividerLeft: "bg-gradient-to-l from-transparent to-blue-200",
    borderDecorative: "bg-gradient-to-r from-blue-200 via-blue-100 to-transparent",
  },
  secondary: {
    bgSection: "bg-gradient-to-b from-purple-50 to-white",
    bgCard: "bg-white",
    textMain: "text-purple-800",
    textSub: "text-purple-500",
    textDesc: "text-gray-500",
    textButton: "text-white",
    bgButton: "bg-purple-600",
    bgButtonHover: "hover:bg-purple-700",
    borderButton: "border-purple-600",
    iconMain: "text-purple-500",
    iconSecondary: "text-purple-300",
    tagBg: "bg-purple-50",
    tagText: "text-purple-600",
    divider: "bg-purple-100",
    dividerRight: "bg-gradient-to-r from-transparent to-purple-200",
    dividerLeft: "bg-gradient-to-l from-transparent to-purple-200",
    borderDecorative: "bg-gradient-to-r from-purple-200 via-purple-100 to-transparent",
  },
  info: {
    bgSection: "bg-gradient-to-b from-cyan-50 to-white",
    bgCard: "bg-white",
    textMain: "text-cyan-800",
    textSub: "text-cyan-500",
    textDesc: "text-gray-500",
    textButton: "text-white",
    bgButton: "bg-cyan-600",
    bgButtonHover: "hover:bg-cyan-700",
    borderButton: "border-cyan-600",
    iconMain: "text-cyan-500",
    iconSecondary: "text-cyan-300",
    tagBg: "bg-cyan-50",
    tagText: "text-cyan-600",
    divider: "bg-cyan-100",
    dividerRight: "bg-gradient-to-r from-transparent to-cyan-200",
    dividerLeft: "bg-gradient-to-l from-transparent to-cyan-200",
    borderDecorative: "bg-gradient-to-r from-cyan-200 via-cyan-100 to-transparent",
  },
  success: {
    bgSection: "bg-gradient-to-b from-green-50 to-white",
    bgCard: "bg-white",
    textMain: "text-green-800",
    textSub: "text-green-500",
    textDesc: "text-gray-500",
    textButton: "text-white",
    bgButton: "bg-green-600",
    bgButtonHover: "hover:bg-green-700",
    borderButton: "border-green-600",
    iconMain: "text-green-500",
    iconSecondary: "text-green-300",
    tagBg: "bg-green-50",
    tagText: "text-green-600",
    divider: "bg-green-100",
    dividerRight: "bg-gradient-to-r from-transparent to-green-200",
    dividerLeft: "bg-gradient-to-l from-transparent to-green-200",
    borderDecorative: "bg-gradient-to-r from-green-200 via-green-100 to-transparent",
  },
  warning: {
    bgSection: "bg-gradient-to-b from-yellow-50 to-white",
    bgCard: "bg-white",
    textMain: "text-yellow-800",
    textSub: "text-yellow-500",
    textDesc: "text-gray-500",
    textButton: "text-white",
    bgButton: "bg-yellow-500",
    bgButtonHover: "hover:bg-yellow-600",
    borderButton: "border-yellow-500",
    iconMain: "text-yellow-500",
    iconSecondary: "text-yellow-300",
    tagBg: "bg-yellow-50",
    tagText: "text-yellow-600",
    divider: "bg-yellow-100",
    dividerRight: "bg-gradient-to-r from-transparent to-yellow-200",
    dividerLeft: "bg-gradient-to-l from-transparent to-yellow-200",
    borderDecorative: "bg-gradient-to-r from-yellow-200 via-yellow-100 to-transparent",
  },
  danger: {
    bgSection: "bg-gradient-to-b from-red-50 to-white",
    bgCard: "bg-white",
    textMain: "text-red-800",
    textSub: "text-red-500",
    textDesc: "text-gray-500",
    textButton: "text-white",
    bgButton: "bg-red-600",
    bgButtonHover: "hover:bg-red-700",
    borderButton: "border-red-600",
    iconMain: "text-red-500",
    iconSecondary: "text-red-300",
    tagBg: "bg-red-50",
    tagText: "text-red-600",
    divider: "bg-red-100",
    dividerRight: "bg-gradient-to-r from-transparent to-red-200",
    dividerLeft: "bg-gradient-to-l from-transparent to-red-200",
    borderDecorative: "bg-gradient-to-r from-red-200 via-red-100 to-transparent",
  },
  gray: {
    bgSection: "bg-gradient-to-b from-gray-50 to-white",
    bgCard: "bg-gray-50",
    textMain: "text-gray-800",
    textSub: "text-gray-500",
    textDesc: "text-gray-400",
    textButton: "text-gray-800",
    bgButton: "bg-gray-200",
    bgButtonHover: "hover:bg-gray-300",
    borderButton: "border-gray-300",
    iconMain: "text-gray-400",
    iconSecondary: "text-gray-300",
    tagBg: "bg-gray-100",
    tagText: "text-gray-600",
    divider: "bg-gray-200",
    dividerRight: "bg-gradient-to-r from-transparent to-gray-200",
    dividerLeft: "bg-gradient-to-l from-transparent to-gray-200",
    borderDecorative: "bg-gradient-to-r from-gray-200 via-gray-100 to-transparent",
  },
};

const DarkColorMap: ThemeColorMap = {
  primary: {
    bgSection: "bg-gradient-to-b from-slate-900 to-gray-900",
    bgCard: "bg-slate-800",
    textMain: "text-blue-200",
    textSub: "text-blue-400",
    textDesc: "text-gray-400",
    textButton: "text-white",
    bgButton: "bg-blue-800",
    bgButtonHover: "hover:bg-blue-900",
    borderButton: "border-blue-700",
    iconMain: "text-blue-300",
    iconSecondary: "text-blue-500",
    tagBg: "bg-blue-900",
    tagText: "text-blue-200",
    divider: "bg-blue-900",
    dividerRight: "bg-gradient-to-r from-transparent to-blue-900",
    dividerLeft: "bg-gradient-to-l from-transparent to-blue-900",
    borderDecorative: "bg-gradient-to-r from-blue-900 via-blue-800 to-transparent",
  },
  secondary: {
    bgSection: "bg-gradient-to-b from-purple-900 to-gray-900",
    bgCard: "bg-purple-950",
    textMain: "text-purple-200",
    textSub: "text-purple-400",
    textDesc: "text-gray-400",
    textButton: "text-white",
    bgButton: "bg-purple-800",
    bgButtonHover: "hover:bg-purple-900",
    borderButton: "border-purple-700",
    iconMain: "text-purple-300",
    iconSecondary: "text-purple-500",
    tagBg: "bg-purple-900",
    tagText: "text-purple-200",
    divider: "bg-purple-900",
    dividerRight: "bg-gradient-to-r from-transparent to-purple-900",
    dividerLeft: "bg-gradient-to-l from-transparent to-purple-900",
    borderDecorative: "bg-gradient-to-r from-purple-900 via-purple-800 to-transparent",
  },
  info: {
    bgSection: "bg-gradient-to-b from-cyan-900 to-gray-900",
    bgCard: "bg-cyan-950",
    textMain: "text-cyan-200",
    textSub: "text-cyan-400",
    textDesc: "text-gray-400",
    textButton: "text-white",
    bgButton: "bg-cyan-800",
    bgButtonHover: "hover:bg-cyan-900",
    borderButton: "border-cyan-700",
    iconMain: "text-cyan-300",
    iconSecondary: "text-cyan-500",
    tagBg: "bg-cyan-900",
    tagText: "text-cyan-200",
    divider: "bg-cyan-900",
    dividerRight: "bg-gradient-to-r from-transparent to-cyan-900",
    dividerLeft: "bg-gradient-to-l from-transparent to-cyan-900",
    borderDecorative: "bg-gradient-to-r from-cyan-900 via-cyan-800 to-transparent",
  },
  success: {
    bgSection: "bg-gradient-to-b from-green-900 to-gray-900",
    bgCard: "bg-green-950",
    textMain: "text-green-200",
    textSub: "text-green-400",
    textDesc: "text-gray-400",
    textButton: "text-white",
    bgButton: "bg-green-800",
    bgButtonHover: "hover:bg-green-900",
    borderButton: "border-green-700",
    iconMain: "text-green-300",
    iconSecondary: "text-green-500",
    tagBg: "bg-green-900",
    tagText: "text-green-200",
    divider: "bg-green-900",
    dividerRight: "bg-gradient-to-r from-transparent to-green-900",
    dividerLeft: "bg-gradient-to-l from-transparent to-green-900",
    borderDecorative: "bg-gradient-to-r from-green-900 via-green-800 to-transparent",
  },
  warning: {
    bgSection: "bg-gradient-to-b from-yellow-900 to-gray-900",
    bgCard: "bg-yellow-950",
    textMain: "text-yellow-200",
    textSub: "text-yellow-400",
    textDesc: "text-gray-400",
    textButton: "text-white",
    bgButton: "bg-yellow-800",
    bgButtonHover: "hover:bg-yellow-900",
    borderButton: "border-yellow-700",
    iconMain: "text-yellow-300",
    iconSecondary: "text-yellow-500",
    tagBg: "bg-yellow-900",
    tagText: "text-yellow-200",
    divider: "bg-yellow-900",
    dividerRight: "bg-gradient-to-r from-transparent to-yellow-900",
    dividerLeft: "bg-gradient-to-l from-transparent to-yellow-900",
    borderDecorative: "bg-gradient-to-r from-yellow-900 via-yellow-800 to-transparent",
  },
  danger: {
    bgSection: "bg-gradient-to-b from-red-900 to-gray-900",
    bgCard: "bg-red-950",
    textMain: "text-red-200",
    textSub: "text-red-400",
    textDesc: "text-gray-400",
    textButton: "text-white",
    bgButton: "bg-red-800",
    bgButtonHover: "hover:bg-red-900",
    borderButton: "border-red-700",
    iconMain: "text-red-300",
    iconSecondary: "text-red-500",
    tagBg: "bg-red-900",
    tagText: "text-red-200",
    divider: "bg-red-900",
    dividerRight: "bg-gradient-to-r from-transparent to-red-900",
    dividerLeft: "bg-gradient-to-l from-transparent to-red-900",
    borderDecorative: "bg-gradient-to-r from-red-900 via-red-800 to-transparent",
  },
  gray: {
    bgSection: "bg-gradient-to-b from-gray-900 to-gray-800",
    bgCard: "bg-gray-800",
    textMain: "text-gray-200",
    textSub: "text-gray-400",
    textDesc: "text-gray-400",
    textButton: "text-white",
    bgButton: "bg-gray-700",
    bgButtonHover: "hover:bg-gray-600",
    borderButton: "border-gray-600",
    iconMain: "text-gray-400",
    iconSecondary: "text-gray-500",
    tagBg: "bg-gray-900",
    tagText: "text-gray-200",
    divider: "bg-gray-900",
    dividerRight: "bg-gradient-to-r from-transparent to-gray-900",
    dividerLeft: "bg-gradient-to-l from-transparent to-gray-900",
    borderDecorative: "bg-gradient-to-r from-gray-900 via-gray-800 to-transparent",
  },
};

// 主流互联网科技网站色板体系
export const BasicColorMap: Record<SectionTheme, ThemeColorMap> = {
  light: LightColorMap,
  dark: DarkColorMap,
  system: {
    // 可根据实际需求调整，默认复用 light 配置
    primary: { ...LightColorMap.primary },
    secondary: { ...LightColorMap.secondary },
    info: { ...LightColorMap.info },
    success: { ...LightColorMap.success },
    warning: { ...LightColorMap.warning },
    danger: { ...LightColorMap.danger },
    gray: { ...LightColorMap.gray },
  },
};
